### ISSUE TITLE
How can I change the interval for when the checks are performed?

### ISSUE THREAD

**Issue by ntoporcov** [caarlos0/speedtest-exporter#9]
I would like to shorten the interval for checks from 30min

**Comment by caarlos0** [comment]
theres a `--refresh-interval` flag for it.

**Comment by phmayer** [comment]
i was also wondering how i could change the interval in the best way, since there was no mention of it in the readme.  
as an approvement, maybe the `--refresh-interval` flag can be documented better in the readme. :)
